//! Generates the README benchmark tables — markdown on stdout, progress on stderr.
//!
//! One table per fixture size: compiled-query evaluation time per engine for each
//! example selector. This is the compile-once/query-many steady state — each engine's
//! query is compiled once and evaluated against a pre-parsed document, single-threaded
//! (the one exception is the `jsonpath-rfc9535 (rayon)` column: the crate's optional
//! parallel feature, labelled as such). A cell reads `not supported` where an engine
//! cannot express the selector. Node-count parity across engines is asserted before
//! anything is timed, so a non-equivalent comparison fails loudly instead of
//! publishing wrong numbers.
//!
//! The `rayon` feature is compile-time, so one binary cannot measure both the serial
//! and parallel value paths. `just bench-readme` therefore runs this harness twice:
//! a `--features rayon` build with `--rayon-only` emits that column as TSV, and the
//! default build merges it via `--rayon <file>`. Both modes refuse to run in the
//! wrong build, so the serial column can never silently carry parallel numbers.
//!
//! Methodology matches ../backend-harness: min-of-batches wall time (batches sized to
//! ~20 ms over a ~1.2 s window) — the least-noise quick point estimate. Trust it to
//! ±10%; the criterion suite is the instrument for fine-grained A/Bs.

use serde_json::Value;
use std::collections::HashMap;
use std::hint::black_box;
use std::time::{Duration, Instant};

/// One table row: the RFC 9535 selector (the row label, run by every RFC engine) and
/// the Goessner translation `jsonpath_lib` needs (`None` = it cannot express it).
struct Case {
    rfc: &'static str,
    goessner: Option<&'static str>,
}

/// Only unambiguously-equivalent selections (mirrors benches/comparison.rs — no
/// `$..*`, whose recursive-wildcard node count differs between dialects).
const CASES: &[Case] = &[
    Case {
        rfc: "$.store.book[0].title",
        goessner: Some("$.store.book[0].title"),
    },
    Case {
        rfc: "$.store.book[*].author",
        goessner: Some("$.store.book[*].author"),
    },
    Case {
        rfc: "$..price",
        goessner: Some("$..price"),
    },
    Case {
        rfc: "$.store.book[*].reviews[*].rating",
        goessner: Some("$.store.book[*].reviews[*].rating"),
    },
    Case {
        rfc: "$.store.book[?@.price < 10]",
        goessner: Some("$.store.book[?(@.price < 10)]"),
    },
    Case {
        rfc: "$.store.book[0].reviews[?@.rating >= 4]",
        goessner: Some("$.store.book[0].reviews[?(@.rating >= 4)]"),
    },
    Case {
        rfc: r#"$.store.book[?search(@.title, "Number 1")]"#,
        goessner: None, // jsonpath_lib has no regex functions.
    },
];

/// `(size label, fixture file)` — the sizes the README story uses.
const FIXTURES: &[(&str, &str)] = &[
    ("25k", "bookstore-25k.json"),
    ("100k", "bookstore-100k.json"),
];

/// Per-`(size, selector)` timings from the `--features rayon` pass.
type RayonData = HashMap<(String, String), f64>;

/// A table cell: a measured time, or the engine cannot express the selector.
enum Cell {
    Nanos(f64),
    Unsupported,
}

fn main() {
    let mut args = std::env::args().skip(1);
    match args.next().as_deref() {
        None => emit_table(None),
        Some("--rayon") => {
            let path = args.next().expect("--rayon takes the TSV file the rayon pass wrote");
            emit_table(Some(load_rayon_data(&path)));
        }
        Some("--rayon-only") => emit_rayon_only(),
        Some(other) => panic!("unknown argument `{other}` (expected --rayon <file> or --rayon-only)"),
    }
}

/// Loads a fixture as `(document, megabytes)`.
fn load(file: &str) -> (Value, f64) {
    let manifest = env!("CARGO_MANIFEST_DIR");
    let text = std::fs::read_to_string(format!("{manifest}/../data/{file}"))
        .expect("run `just bench-fixtures` first: benches/data fixture missing");
    let megabytes = text.len() as f64 / 1e6;
    let document = serde_json::from_str(&text).expect("fixture parses");
    (document, megabytes)
}

/// The full markdown tables, with the rayon column merged in when provided.
fn emit_table(rayon: Option<RayonData>) {
    assert!(
        !cfg!(feature = "rayon"),
        "table mode must be built WITHOUT the rayon feature — the serial column \
         would silently carry parallel numbers (use `just bench-readme`)"
    );
    println!(
        "Compiled-query evaluation over a pre-parsed document — the compile-once, \
         query-many steady state. Parse cost excluded; every engine runs \
         single-threaded{}. Generated by `just bench-readme`; absolute numbers are \
         machine-specific, so read the ratios.",
        if rayon.is_some() {
            " (except the `rayon` column, the crate's optional parallel feature)"
        } else {
            ""
        }
    );
    for &(label, file) in FIXTURES {
        let (document, megabytes) = load(file);
        println!();
        println!("### {label}-book document ({megabytes:.1} MB)");
        println!();
        let rayon_header = if rayon.is_some() {
            " `jsonpath-rfc9535` (`rayon`) |"
        } else {
            ""
        };
        println!(
            "| Selector | Results | `jsonpath-rfc9535` |{rayon_header} `jsonpath_lib` | `serde_json_path` | `jsonpath-rust` |"
        );
        println!(
            "|---|---:|---:|{}---:|---:|---:|",
            if rayon.is_some() { "---:|" } else { "" }
        );
        for case in CASES {
            eprintln!("measuring {label} / {}", case.rfc);
            let (results, mut cells) = measure_case(case, &document, label);
            if let Some(data) = &rayon {
                let nanos = *data
                    .get(&(label.to_owned(), case.rfc.to_owned()))
                    .expect("the rayon pass measured every (size, selector) pair");
                cells.insert(1, Cell::Nanos(nanos));
            }
            println!(
                "| `{}` | {} | {} |",
                case.rfc,
                group_thousands(results),
                render(&cells).join(" | ")
            );
        }
    }
    println!();
    println!(
        "`jsonpath_lib` (Goessner dialect) evaluates the equivalent `?(...)` filter \
         form; `not supported` means the engine cannot express the selector \
         (`search()` is an RFC 9535 function extension). Bold marks the fastest \
         cell in each row.{}",
        if rayon.is_some() {
            " The `rayon` column is `jsonpath-rfc9535` with its optional parallel \
             feature enabled — multi-threaded, so not a like-for-like engine \
             comparison; it shows what the feature buys on large documents."
        } else {
            ""
        }
    );
}

/// The rayon pass: times only `jsonpath-rfc9535`'s parallel value path, one TSV line
/// (`size<TAB>selector<TAB>nanoseconds`) per `(size, selector)` pair.
fn emit_rayon_only() {
    assert!(
        cfg!(feature = "rayon"),
        "--rayon-only requires building with `--features rayon` (use `just bench-readme`)"
    );
    for &(label, file) in FIXTURES {
        let (document, _megabytes) = load(file);
        for case in CASES {
            eprintln!("measuring {label} / {} (rayon)", case.rfc);
            let query = jsonpath_rfc9535::JsonPath::parse(case.rfc)
                .expect("jsonpath-rfc9535 compiles the case");
            assert!(
                !query.query_values(&document).is_empty(),
                "`{}` over {label} selects nothing — a vacuous row",
                case.rfc
            );
            let nanos = best_of_batches(|| query.query_values(black_box(&document)).len());
            println!("{label}\t{}\t{nanos}", case.rfc);
        }
    }
}

/// Parses the TSV the rayon pass wrote.
fn load_rayon_data(path: &str) -> RayonData {
    let text = std::fs::read_to_string(path).expect("the rayon pass TSV exists");
    text.lines()
        .map(|line| {
            let mut fields = line.splitn(3, '\t');
            let size = fields.next().expect("TSV size field").to_owned();
            let rfc = fields.next().expect("TSV selector field").to_owned();
            let nanos = fields
                .next()
                .expect("TSV nanos field")
                .parse()
                .expect("TSV nanos parses");
            ((size, rfc), nanos)
        })
        .collect()
}

/// Times every engine on one selector, asserting node-count parity first so the
/// table can never carry a non-equivalent comparison. Returns the (agreed) node
/// count alongside the timing cells — the table's Results column.
fn measure_case(case: &Case, document: &Value, size: &str) -> (usize, Vec<Cell>) {
    let rfc = case.rfc;

    let ours = jsonpath_rfc9535::JsonPath::parse(rfc).expect("jsonpath-rfc9535 compiles the case");
    let expected = ours.query_values(document).len();
    assert!(expected > 0, "`{rfc}` over {size} selects nothing — a vacuous row");

    let lib = case.goessner.map(|goessner| {
        let compiled =
            jsonpath_lib::Compiled::compile(goessner).expect("jsonpath_lib compiles the case");
        let count = compiled.select(document).map_or(0, |nodes| nodes.len());
        assert_eq!(count, expected, "jsonpath_lib disagrees on `{rfc}` over {size}");
        compiled
    });

    let sjp = serde_json_path::JsonPath::parse(rfc).expect("serde_json_path compiles the case");
    assert_eq!(
        sjp.query(document).len(),
        expected,
        "serde_json_path disagrees on `{rfc}` over {size}"
    );

    let jsr = jsonpath_rust::parser::parse_json_path(rfc).expect("jsonpath-rust compiles the case");
    let jsr_count = jsonpath_rust::query::js_path_process(&jsr, document).map_or(0, |n| n.len());
    assert_eq!(jsr_count, expected, "jsonpath-rust disagrees on `{rfc}` over {size}");

    let cells = vec![
        Cell::Nanos(best_of_batches(|| {
            ours.query_values(black_box(document)).len()
        })),
        lib.map_or(Cell::Unsupported, |compiled| {
            Cell::Nanos(best_of_batches(|| {
                compiled.select(black_box(document)).map_or(0, |n| n.len())
            }))
        }),
        Cell::Nanos(best_of_batches(|| {
            sjp.query(black_box(document)).all().len()
        })),
        Cell::Nanos(best_of_batches(|| {
            jsonpath_rust::query::js_path_process(black_box(&jsr), black_box(document))
                .map_or(0, |n| n.len())
        })),
    ];
    (expected, cells)
}

/// `1234567` → `1,234,567`.
fn group_thousands(n: usize) -> String {
    let digits = n.to_string();
    let mut grouped = String::with_capacity(digits.len() + digits.len() / 3);
    for (index, digit) in digits.chars().enumerate() {
        if index > 0 && (digits.len() - index) % 3 == 0 {
            grouped.push(',');
        }
        grouped.push(digit);
    }
    grouped
}

/// Formats a row's cells, bolding the fastest measured time.
fn render(cells: &[Cell]) -> Vec<String> {
    let fastest = cells
        .iter()
        .filter_map(|cell| match cell {
            Cell::Nanos(ns) => Some(*ns),
            Cell::Unsupported => None,
        })
        .fold(f64::INFINITY, f64::min);
    cells
        .iter()
        .map(|cell| match cell {
            Cell::Nanos(ns) if *ns <= fastest => format!("**{}**", fmt(*ns)),
            Cell::Nanos(ns) => fmt(*ns),
            Cell::Unsupported => "not supported".to_owned(),
        })
        .collect()
}

/// Min-of-batches wall time per call, in nanoseconds (see ../backend-harness).
fn best_of_batches(mut run: impl FnMut() -> usize) -> f64 {
    let warm_until = Instant::now() + Duration::from_millis(200);
    let mut sink = 0usize;
    while Instant::now() < warm_until {
        sink = sink.wrapping_add(run());
    }
    let probe = Instant::now();
    sink = sink.wrapping_add(run());
    let one = probe.elapsed().as_nanos().max(1) as f64;
    let batch = ((20_000_000.0 / one).ceil() as usize).clamp(1, 5_000_000);
    let mut best = f64::INFINITY;
    let measure_until = Instant::now() + Duration::from_millis(1200);
    while Instant::now() < measure_until {
        let start = Instant::now();
        for _ in 0..batch {
            sink = sink.wrapping_add(run());
        }
        best = best.min(start.elapsed().as_nanos() as f64 / batch as f64);
    }
    black_box(sink);
    best
}

fn fmt(ns: f64) -> String {
    if ns >= 1e6 {
        format!("{:.2} ms", ns / 1e6)
    } else if ns >= 1e3 {
        format!("{:.1} µs", ns / 1e3)
    } else {
        format!("{ns:.0} ns")
    }
}
